// arrary 
// é um grupo de valors. Servem para guardadrmos diferentes valoresem uma única variavel.
/*var Videogame = ['Switch ' , 'PS4' , 'XBOX'];
var numeros = [ 1,2,3]
console.log(Videogame[0])
console.log(Videogame[1])
console.log(Videogame[3])

console.log(numeros[0]) + numeros([2])*/

/*var i = 0;
while(i<10) {
    console.log(i)
    i = i + 1 
}*/

/*for (var i = 0; i < 10; i = i+1){
    console.log(i)
} */

var Videogame = ['Switch ' ,'PS4' , 'XBOX']

// ForEach
// forEach e um metodo que executa uma função para cada item cada item array. E uma forma mais simples de utilizarmos um loop com arrays 
/*Videogame.forEach(function(a,b,c){
    console.log(a,b,c)*/


var futebol = ['1958' , '1962' , '1970' , '1994' , '2002']
console.log(`o barsil ganhou a copa` + c)
    